### ISSUE TITLE
CLI: no way to disambiguate package vs author

### ISSUE THREAD

**Issue by ljharb** [maddhruv/npmtotal#3]
`browserify` is both a package and an org, and `npx npmtotal browserify` reports nothing - which seems strange.

`npx npmtotal substack` (which is both a package and a user) presumably presents a similar problem.

**Comment by maddhruv** [comment]
In the [1.2.0](https://github.com/maddhruv/npmtotal/releases/tag/1.2.0) release, I have added the author name and packages as part of separate cli options.

**Comment by ljharb** [comment]
(requiring `--author` or `--package` is a breaking change; it should have been v2)

However, this addresses the issue, thanks!
