### ISSUE TITLE
CLI: output messes with the prompt

### ISSUE THREAD

**Issue by ljharb** [maddhruv/npmtotal#4]
In the same way that using `printf` causes the next prompt to not necessarily be *after* the output vs `echo`, whatever you're using to output causes my next prompt to appear in the middle of it, instead of after it.

Perhaps this is because you're not stopping the progress bar until after you've console.logged the results?

**Comment by maddhruv** [comment]
With the [1.2.0](https://github.com/maddhruv/npmtotal/releases/tag/1.2.0) release I feel the issue is fixed now.
Please check

**Comment by ljharb** [comment]
This issue is now addressed, thanks!
